version: '2'
services:
    consul:
        image: consul:v0.6.4
        network_mode: "host"
        ports:
            - 8300:8300
            - 8500:8500
            - 8600:8600
        command: consul agent -dev -bind=127.0.0.1

    consul-config-loader:
        build: .
        network_mode: "host"
        volumes:
            - ./config/:/config
        environment:
            - CONFIG_MODE=filesystem
            - INIT_SLEEP_SECONDS=5
